In [86]:
import pandas as pd
x = pd.DataFrame(['a','b','c','a','b','a'],columns=['x1'])
y = pd.DataFrame(['n','m','p','m','m','p'],columns=['x2'])
z = pd.concat([x,y],axis=1)
print(z)

t = {}
for i in x['x1']:
    t.setdefault(i,0)
    t[i] +=1
t

  x1 x2
0  a  n
1  b  m
2  c  p
3  a  m
4  b  m
5  a  p


{'a': 3, 'b': 2, 'c': 1}

In [116]:
bag = {}
for i,j in zip(z['x1'],z['x2']):
    bag.setdefault(i,j)
    t = {bag[i]:0}
    t.setdefault(j,0)
bag

{'a': 'n', 'b': 'm', 'c': 'p'}

In [44]:
d = {a:{b:c for b,c in zip(y,z)} for a in x}
d = {a:{b:c for b,c in zip(y,z)} for a in x}
d = {b:c for b in y for c in z}

{'a': {'m': 2, 'n': 1, 'p': 3},
 'b': {'m': 2, 'n': 1, 'p': 3},
 'c': {'m': 2, 'n': 1, 'p': 3}}

In [101]:
# 如何构建字典的字典  字典中不能有相同的健
p ={'x':{'a':2,'c':3},'y':{'b':4}}
t = p['x']
t['a']=11
print(t,p)

{'a': 11, 'c': 3} {'x': {'a': 11, 'c': 3}, 'y': {'b': 4}}


In [1]:
import graphviz

In [5]:
import numpy as np
a = np.arange(9).reshape(3,3)
b = np.arange(6).reshape(2,3)
print(a,b)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]
 [3 4 5]]


In [10]:
np.dot(a,b.T)

array([[ 5, 14],
       [14, 50],
       [23, 86]])

In [14]:
np.matmul(a,b.T)

array([[ 5, 14],
       [14, 50],
       [23, 86]])